"""Pydantic models and domain enums for copywriting generation."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field, field_validator, model_validator


class Platform(str, Enum):
    """Supported marketing platforms."""
    LINKEDIN = "linkedin"
    INSTAGRAM = "instagram"
    EMAIL = "email"
    TWITTER = "twitter"

    @classmethod
    def _missing_(cls, value: Any) -> Any:
        """Allow case-insensitive lookups and common aliases."""
        if isinstance(value, str):
            normalized = value.strip().lower()
            if normalized in ("x", "x/twitter", "twitter/x"):
                return cls.TWITTER
            for member in cls:
                if member.value == normalized:
                    return member
        return None


class Tone(str, Enum):
    """Supported copywriting tones."""
    PROFESSIONAL = "professional"
    WITTY = "witty"
    FRIENDLY = "friendly"
    LUXURY = "luxury"
    EXCITING = "exciting"
    PERSUASIVE = "persuasive"
    CASUAL = "casual"

    @classmethod
    def _missing_(cls, value: Any) -> Any:
        """Allow case-insensitive lookups."""
        if isinstance(value, str):
            normalized = value.strip().lower()
            for member in cls:
                if member.value == normalized:
                    return member
        return None


class GenerationRequest(BaseModel):
    """Input parameters for a copywriting generation task."""
    product_name: str = Field(
        ...,
        description="Name of the product or service",
        min_length=2,
    )
    product_description: str = Field(
        ...,
        description="Detailed description of features, benefits, and target audience",
        min_length=10,
    )
    platform: Platform = Field(
        ...,
        description="Target distribution channel (e.g. linkedin, instagram, email, twitter)",
    )
    tone: Tone = Field(
        ...,
        description="Desired voice and emotional appeal (e.g. professional, witty, luxury)",
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature for creativity vs predictability (0.0 to 2.0)",
    )
    top_p: float = Field(
        default=0.9,
        ge=0.0,
        le=1.0,
        description="Nucleus sampling probability threshold (0.0 to 1.0)",
    )
    max_output_tokens: int = Field(
        default=500,
        ge=50,
        le=2000,
        description="Maximum tokens generated by the model (50 to 2000)",
    )

    @field_validator("product_name")
    @classmethod
    def validate_product_name(cls, v: str) -> str:
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("Product name cannot be empty or purely whitespace.")
        if len(cleaned) < 2:
            raise ValueError("Product name must be at least 2 characters long.")
        return cleaned

    @field_validator("product_description")
    @classmethod
    def validate_product_description(cls, v: str) -> str:
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("Product description cannot be empty or purely whitespace.")
        if len(cleaned) < 10:
            raise ValueError("Product description must contain meaningful text (at least 10 characters).")
        return cleaned


class GenerationResponse(BaseModel):
    """Structured response containing generated copy and associated metadata."""
    product_name: str
    platform: Platform
    tone: Tone
    generated_copy: str
    model_used: str
    temperature: float
    top_p: float
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    )
    character_count: int = 0
    word_count: int = 0

    @model_validator(mode="after")
    def compute_counts(self) -> "GenerationResponse":
        """Automatically calculate character and word counts if not provided."""
        text = self.generated_copy or ""
        if not self.character_count:
            self.character_count = len(text)
        if not self.word_count:
            self.word_count = len(text.split())
        return self
